name: Groupmembers service Workflow

on:
  push:
    branches:
      - main
      - branches

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_TOKEN: ${{secrets.GRADLE_TOKEN}}


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Gradle
      run: chmod +x ./gradlew
      env:
        GRADLE_OPTS: '-Dorg.gradle.daemon=false'
        GRADLE_USER_HOME: './gradle'
        PAT: ${{env.GRADLE_TOKEN}}

#  lint:
#    runs-on: ubuntu-latest

#    steps:
#    - name: Checkout repository
#      uses: actions/checkout@v2

#    - name: Set up JDK 11
#      uses: actions/setup-java@v2
#      with:
#        distribution: 'adopt'
#        java-version: '11'

#    - name: Run Spotless (code formatter)
#      run: ./gradlew spotlessCheck

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Run tests with Gradle
      run: ./gradlew test
