name: Groupmembers service Workflow

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_TOKEN: ${{secrets.GRADLE_TOKEN}}


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Clean Build with Gradle
      run: |
        chmod +x ./gradlew && 
        ./gradlew clean build
        
      env:
        GRADLE_OPTS: '-Dorg.gradle.daemon=false'
        GRADLE_USER_HOME: './gradle'
        PAT: ${{env.GRADLE_TOKEN}}

#  lint:
#    runs-on: ubuntu-latest

#    steps:
#    - name: Checkout repository
#      uses: actions/checkout@v2

#    - name: Set up JDK 11
#      uses: actions/setup-java@v2
#      with:
#        distribution: 'adopt'
#        java-version: '11'

#    - name: Run Spotless (code formatter)
#      run: ./gradlew spotlessCheck

  test:
    runs-on: ubuntu-latest
    env:
      GRADLE_TOKEN: ${{secrets.GRADLE_TOKEN}}
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Run tests with Gradle
      run: |
        chmod +x ./gradlew && 
        ./gradlew clean test
      env:
        GRADLE_OPTS: '-Dorg.gradle.daemon=false'
        GRADLE_USER_HOME: './gradle'
        PAT: ${{env.GRADLE_TOKEN}}
    - name: Sonarcloud scan
      run: |
        chmod +x ./gradlew && 
        ./gradlew clean build jacocoTestReport jacocoTestCoverageVerification sonarqube -Dsonar.organization=${{env.SONAR_ORG_KEY}} -Dsonar.projectKey=${{env.SONAR_PROJECT_KEY}} -Dsonar.host.url=${{env.SONAR_HOST_URL}} -Dsonar.login=${{env.SONAR_TOKEN}}
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        GRADLE_TOKEN: ${{secrets.GRADLE_TOKEN}}
